### ISSUE TITLE
Error during installation packages with pip

### ISSUE THREAD

**Issue by be4zad** [hafez-notebook/server#2] opened 2021-11-28 07:48 UTC
An error occurred while installing. There seems to be a bug in the code.

`Collecting asgiref==3.4.1
  Using cached asgiref-3.4.1-py3-none-any.whl (25 kB)
Collecting Django==3.2.9
  Using cached Django-3.2.9-py3-none-any.whl (7.9 MB)
Collecting mysqlclient==2.1.0
  Using cached mysqlclient-2.1.0.tar.gz (87 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-pjo6usq0/mysqlclient_75020efea9e6498ab090c548c2e1863c/setup.py'"'"'; __file__='"'"'/tmp/pip-install-pjo6usq0/mysqlclient_75020efea9e6498ab090c548c2e1863c/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-09f2x0xo
         cwd: /tmp/pip-install-pjo6usq0/mysqlclient_75020efea9e6498ab090c548c2e1863c/
    Complete output (15 lines):
    /bin/sh: line 1: mysql_config: command not found
    /bin/sh: line 1: mariadb_config: command not found
    /bin/sh: line 1: mysql_config: command not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-pjo6usq0/mysqlclient_75020efea9e6498ab090c548c2e1863c/setup.py", line 15, in <module>
        metadata, options = get_config()
      File "/tmp/pip-install-pjo6usq0/mysqlclient_75020efea9e6498ab090c548c2e1863c/setup_posix.py", line 70, in get_config
        libs = mysql_config("libs")
      File "/tmp/pip-install-pjo6usq0/mysqlclient_75020efea9e6498ab090c548c2e1863c/setup_posix.py", line 31, in mysql_config
        raise OSError("{} not found".format(_mysql_config_path))
    OSError: mysql_config not found
    mysql_config --version
    mariadb_config --version
    mysql_config --libs
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/de/79/d02be3cb942afda6c99ca207858847572e38146eb73a7c4bfe3bdf154626/mysqlclient-2.1.0.tar.gz#sha256=973235686f1b720536d417bf0a0d39b4ab3d5086b2b6ad5e6752393428c02b12 (from https://pypi.org/simple/mysqlclient/) (requires-python:>=3.5). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement mysqlclient==2.1.0
ERROR: No matching distribution found for mysqlclient==2.1.0
`

**Comment by shmf1385** [comment] 2021-11-28 18:15
do you use GNU/Linux?

**Comment by behDev** [comment] 2021-11-29 06:00
#
Duplicate of #

**Comment by be4zad** [comment] 2021-11-29 06:02
@SHMF1385 yes, of course i use arch linux.

**Comment by shmf1385** [comment] 2021-11-29 06:12
you should to install this packages for debian and arch based distros:
`python3-dev default-libmysqlclient-dev build-essential`

and this packages for Redhat based distros
`python3-devel mysql-devel`

Likely debian package names

**Comment by be4zad** [comment] 2021-11-29 06:20
@SHMF1385 pacman response:
`error: target not found: python3-dev, default-libmysqlclient-dev, build-essential
`

**Comment by shmf1385** [comment] 2021-11-29 06:49
Try this:

`pacman -S python3-mysqlclient` or `pacman -S python-mysqlclient`

**Comment by be4zad** [comment] 2021-11-29 08:34
@SHMF1385 Yes, `python-mysqlclinet` worked. we are must write wiki for install this project in distros .

**Closed as completed** 2021-11-29 08:34 UTC
